### ISSUE TITLE
CLOUDY path: adding the option to choose a different path for the CLOUDY executable

### ISSUE THREAD

**Issue by raulorteg** [raulorteg/pyNublado#16]
Currently the path to cloudy executable is static, this should be changed to allow for users to specify where the cloudy executable is installed in their machine.

e.g reading the cloudy executable path from the input of a class or from a json config file, common/setting.py file

**Comment by eor** [comment]
If we are happy with having this in common/settings.py, we could close this issue.

**Comment by raulorteg** [comment]
> 

I agree, lets close it
