### ISSUE TITLE
Enabling the queue manager to monitor / check / kill model runs

### ISSUE THREAD

**Issue by eor** [raulorteg/pyNublado#30]
It might be a good idea to enhance the queue manager's _run_model mechanism, so that we can better monitor and interact with the subprocesses that handle the cloudy runs.  [This blog post](https://eli.thegreenplace.net/2017/interacting-with-a-long-running-child-process-in-python/) might be helpful to that end.

It would be nice to be able to have some kind of exception handling, automated checks, and possibly the ability to kill runs if they exceed a specified maximum runtime.

We should be able to use subprocess.Popen() afterall, as we can change directories with either os.chdir() or directly with Popen("command", pwd='../samples/sample/N123/todo').

**Comment by aswinpvijayan** [comment]
The package [Pebble](https://pythonhosted.org/Pebble/) might also be useful for monitoring jobs

**Comment by eor** [comment]
Issues resolved for now
