### ISSUE TITLE
Dataproducts: Outcome dataframe (inputs + output status)

### ISSUE THREAD

**Issue by raulorteg** [raulorteg/pyNublado#35]
### Dataproducts: Outcome dataframe (inputs + output status)
* given path to N_xxxx/ folder:
       * check if todo/ is empty, else print warning
       * parse all models in done/
       * for each model look how it exited: ok, aborted, ....
       * create a table containing id (hash), inputs, exit_code
       * save the table at N_xxxx/ as pandas object

**Comment by eor** [comment]
Can we add the run time (for the successful runs) to the output data frame?
