### ISSUE TITLE
Adding dust-to-metal ratio as a cloudy input parameter

### ISSUE THREAD

**Issue by aswinpvijayan** [raulorteg/pyNublado#48]
Adding this means that we need to explicitly state the abundance of each metal within the model.in file. Workflow would be something like: define a function dust_to_metal(), takes in the parameter range from say 0-0.6 and depending on latest abundance and depletion patterns from the nearby Universe, the metal abundances are written into the input file.

**Comment by eor** [comment]
I think this new parameter should also be mentioned and briefly described in the `Readme.md` file.
